# Generated by Django 5.1.4 on 2026-04-22 19:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idu', models.CharField(db_index=True, max_length=20, unique=True)),
                ('code_dep', models.CharField(db_index=True, max_length=3)),
                ('code_com', models.CharField(db_index=True, max_length=5)),
                ('nom_com', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(db_index=True, max_length=2)),
                ('numero', models.CharField(max_length=4)),
                ('feuille', models.IntegerField(default=0)),
                ('contenance', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(db_index=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Parcelle cadastrale',
                'indexes': [models.Index(fields=['code_dep', 'code_com'], name='cadastre_pa_code_de_50db8f_idx')],
            },
        ),
    ]
